FROM python:3.11

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

# Install curl
RUN apt-get update && apt-get install -y curl

# Install kubectl
RUN curl -LO "https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl"

RUN chmod +x kubectl

RUN mv kubectl /usr/local/bin/

COPY . .

EXPOSE 5000

CMD ["python", "app.py"]