apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: kubedeploy

spec:
  replicas: 2

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
      - name: frontend
        image: prabhjotkaur9009/frontend:v10

        ports:
        - containerPort: 80